/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/k20YpsBWbsw
 */
"use client"

import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"
import ProjectCard from "./project-card"
import Autoplay from "embla-carousel-autoplay"
import React from "react"


export function CaseStudies() {
  const plugin = React.useRef(
    Autoplay({ delay: 2000, stopOnInteraction: true })
  )
  return (
    <section className="w-full py-12" id="case-studies">
      <div className="container grid lg:grid-cols-2 items-center gap-12 px-4">
        <div className="space-y-4">
          <h2 className="text-3xl font-bold tracking-tight">Case Studies</h2>
          <p className="text-gray-500 dark:text-gray-400">
            Our case studies showcase our work and the value we bring to our customers. Explore the stories behind our
            successful projects.
          </p>
        </div>
        <div className="flex items-start justify-end">
          <div className="w-full max-w-sm">
            <Carousel
              plugins={[plugin.current]}
              className="w-full max-w-xs"
              onMouseEnter={plugin.current.stop}
              onMouseLeave={plugin.current.reset}
            >
              <CarouselContent className="h-[500px]">
                <CarouselItem >
                  <div className="p-1">
                    <ProjectCard />
                  </div>
                </CarouselItem>
                <CarouselItem>
                  <div className="p-1">
                    <ProjectCard />
                  </div>
                </CarouselItem>
                <CarouselItem>
                  <div className="p-1">
                    <ProjectCard />
                  </div>
                </CarouselItem>
              </CarouselContent>
              <CarouselPrevious />
              <CarouselNext />
            </Carousel>
          </div>
        </div>
      </div>
    </section>
  )
}
