/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SeUYoSNPDSa
 */
import { Avatar } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function ContactForm() {
  return (
    <div className="space-y-8">
      <div className="space-y-2">
        <h2 className="text-3xl font-bold">Contact Us</h2>
        <p className="text-gray-500 dark:text-gray-400">
          We're here to help. Send us a message and we will get back to you as soon as possible.
        </p>
      </div>
      <Card className="space-y-4 p-4">
        <CardHeader>
          <div className="flex items-center">
            <Avatar className="mr-2" src="/placeholder.svg?height=50&width=50" />
            <Badge>Customer Support</Badge>
          </div>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="name">Name</Label>
              <Input id="name" placeholder="Enter your name" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" placeholder="Enter your email" type="email" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="subject">Subject</Label>
              <Input id="subject" placeholder="Enter the subject of your message" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="message">Message</Label>
              <Textarea className="min-h-[100px]" id="message" placeholder="Enter your message" />
            </div>
            <Button>Submit</Button>
          </div>
        </CardContent>
      </Card>
      <div className="text-center">
        <p className="text-gray-500 dark:text-gray-400">
          By submitting this form, you agree to our
          <Link className="underline text-blue-500 dark:text-blue-400" href="#">
            Terms & Conditions
          </Link>
          .{"\n          "}
        </p>
      </div>
    </div>
  )
}
