/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tE0zB6FSEEw
 */
"use client";
import Link from "next/link";
import { ModeToggle } from "../mode-toggle";
import { JSX, SVGProps } from "react";
import { useTheme } from "next-themes";

export function LandingPageHeader() {
  const { resolvedTheme } = useTheme();
  return (
    <header className="w-full py-4 md:py-6">
      <div className="container flex items-center justify-between px-4 md:px-6">
        <div className="flex items-center space-x-4">
          <Link className="flex items-center space-x-2" href="/">
            {/* <HomeIcon className="w-6 h-6" /> */}
            <Logo color={resolvedTheme === "dark" ? "#fff" : "#000"} />
            <span className="font-bold">autom84.fun</span>
          </Link>
        </div>
        <nav className="hidden items-center gap-4 md:flex">
          <Link
            className="flex items-center space-x-1.5 font-medium text-sm/relaxed transition-colors text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
            href="/#features"
          >
            Features
          </Link>
          <Link
            className="flex items-center space-x-1.5 font-medium text-sm/relaxed transition-colors text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
            href="/#case-studies"
          >
            Case studies
          </Link>
          <Link
            className="flex items-center space-x-1.5 font-medium text-sm/relaxed transition-colors text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
            href="/contact"
          >
            Contact
          </Link>
        </nav>
        <div className="flex items-center space-x-4">
          <Link
            // className="inline-flex items-center justify-center rounded-md h-10 bg-green-600 px-5 py-3 text-sm font-medium text-white transition-colors hover:bg-green-800"
            className="bg-primary text-background hover:bg-primary-foreground border border-primary hover:text-primary rounded-md px-5 py-2"
            href="/login"
          >
            Get started
          </Link>
          <div className="flex items-center space-x-2">
            <ModeToggle />
          </div>
        </div>
      </div>
    </header>
  );
}

function HomeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  );
}

const Logo = (props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width={25}
    height={22}
    fill="currentColor"
    {...props}
  >
    <path
      fill="currentColor"
      d="M19.925 2.396h-1.263A2.547 2.547 0 0 0 16.16.4a2.556 2.556 0 0 0-2.577 2.577 2.588 2.588 0 0 0 2.577 2.577 2.573 2.573 0 0 0 2.5-1.996h1.264c1.92 0 3.461 1.567 3.461 3.487a3.466 3.466 0 0 1-3.461 3.46h-3.663l1.263-1.263-.834-.833-2.652 2.678 2.678 2.678.833-.834-1.263-1.263h3.663A4.652 4.652 0 0 0 24.6 7.019c0-2.577-2.097-4.623-4.674-4.623ZM3.15 5.554A2.573 2.573 0 0 0 5.653 3.56h4.926L9.315 4.822l.833.834 2.678-2.678L10.148.3l-.833.833 1.263 1.264H5.677C5.399 1.26 4.388.4 3.176.4A2.588 2.588 0 0 0 .599 2.978C.574 4.392 1.736 5.554 3.151 5.554ZM19.925 16.62a2.588 2.588 0 0 0-2.577 2.577 2.588 2.588 0 0 0 2.577 2.577 2.588 2.588 0 0 0 2.577-2.577 2.571 2.571 0 0 0-2.577-2.577ZM13.155 17.353l1.263 1.263H5.525c-1.92 0-3.46-1.566-3.46-3.486a3.466 3.466 0 0 1 3.46-3.461H8.28c.278 1.136 1.288 1.995 2.501 1.995a2.588 2.588 0 0 0 2.577-2.576A2.588 2.588 0 0 0 10.78 8.51a2.573 2.573 0 0 0-2.501 1.996H5.525a4.652 4.652 0 0 0-4.648 4.648 4.652 4.652 0 0 0 4.648 4.648h8.893l-1.263 1.263.833.834 2.678-2.678-2.678-2.703-.833.834Z"
    />
  </svg>
);
