/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tE0zB6FSEEw
 */
'use client'
import Link from "next/link";
import { ModeToggle } from "../mode-toggle";
import { JSX, SVGProps } from "react";
import {useTheme} from "next-themes";

export function LandingPageHeader() {
  const { resolvedTheme } = useTheme();
  return (
    <header className="w-full py-4 md:py-6">
      <div className="container flex items-center justify-between px-4 md:px-6">
        <div className="flex items-center space-x-4">
          <Link className="flex items-center space-x-2" href="/">
            {/* <HomeIcon className="w-6 h-6" /> */}
            <Logo color={resolvedTheme === "dark" ? "#fff" : "#000"}/>
            <span className="font-bold">autom84.fun</span>
          </Link>
        </div>
        <nav className="hidden items-center gap-4 md:flex">
          <Link
            className="flex items-center space-x-1.5 font-medium text-sm/relaxed transition-colors text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
            href="/#features"
          >
            Features
          </Link>
          <Link
            className="flex items-center space-x-1.5 font-medium text-sm/relaxed transition-colors text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
            href="/#case-studies"
          >
            Case studies
          </Link>
          <Link
            className="flex items-center space-x-1.5 font-medium text-sm/relaxed transition-colors text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
            href="/contact"
          >
            Contact
          </Link>
        </nav>
        <div className="flex items-center space-x-4">
          <Link
            // className="inline-flex items-center justify-center rounded-md h-10 bg-green-600 px-5 py-3 text-sm font-medium text-white transition-colors hover:bg-green-800"
            className="bg-primary text-background hover:bg-primary-foreground border border-primary hover:text-primary rounded-md px-5 py-2" 
            href="/login"
          >
            Get started
          </Link>
          <div className="flex items-center space-x-2">
            <ModeToggle />
          </div>
        </div>
      </div>
    </header>
  );
}

function HomeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  );
}

function Logo(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg 
      {...props} 
      width="25" 
      height="22" 
      viewBox="0 0 25 22" 
      fill={props.color}
      // stroke="currentColor" 
      // strokeWidth="1"
      // strokeLinecap="round"
      // strokeLinejoin="round"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path d="M19.925 2.39616H18.6618C18.4092 1.23407 17.3734 0.400391 16.1608 0.400391C14.7208 0.400391 13.584 1.53722 13.584 2.97721C13.584 4.39193 14.7461 5.55403 16.1608 5.55403C17.3734 5.55403 18.4092 4.69509 18.6618 3.55826H19.925C21.845 3.55826 23.386 5.12456 23.386 7.04454C23.386 8.96452 21.8197 10.5056 19.925 10.5056H16.2619L17.525 9.24241L16.6913 8.40874L14.0387 11.0866L16.7166 13.7645L17.5503 12.9308L16.2871 11.6677H19.9502C22.5018 11.6677 24.5986 9.59609 24.5986 7.01928C24.5986 4.44246 22.5018 2.39616 19.925 2.39616Z" fill="black"/>
      <path d="M3.15059 5.55449C4.36321 5.55449 5.39899 4.69555 5.65162 3.55872H10.5779L9.31474 4.82187L10.1484 5.65554L12.8263 2.97767L10.1484 0.299805L9.31474 1.13348L10.5779 2.39663H5.67688C5.39899 1.2598 4.38847 0.400856 3.17585 0.400856C1.76113 0.400856 0.599037 1.56295 0.599037 2.97767C0.573774 4.3924 1.73587 5.55449 3.15059 5.55449Z" fill="black"/>
      <path d="M19.925 16.6201C18.5102 16.6201 17.3481 17.7822 17.3481 19.1969C17.3481 20.6117 18.5102 21.7738 19.925 21.7738C21.3397 21.7738 22.5018 20.6117 22.5018 19.1969C22.5018 17.7822 21.3649 16.6201 19.925 16.6201Z" fill="black"/>
      <path d="M13.1547 17.3528L14.4179 18.6159H5.52533C3.60535 18.6159 2.06431 17.0496 2.06431 15.1296C2.06431 13.2096 3.63061 11.6686 5.52533 11.6686H8.27899C8.55688 12.8054 9.5674 13.6644 10.78 13.6644C12.1947 13.6644 13.3568 12.5023 13.3568 11.0876C13.3568 9.67284 12.1947 8.51074 10.78 8.51074C9.5674 8.51074 8.53162 9.36968 8.27899 10.5065H5.52533C2.97378 10.5065 0.876953 12.5781 0.876953 15.1549C0.876953 17.7064 2.94851 19.8033 5.52533 19.8033H14.4179L13.1547 21.0664L13.9884 21.9001L16.6663 19.2222L13.9884 16.5191L13.1547 17.3528Z" fill="black"/>
    </svg>
  )
}
